name: CreateFramework
on:
  push:
    branches:
    - main
jobs:
  build:
    name: Build iPhone simulator
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild archive \
          -scheme CICDFramework \
          -configuration Release \
          -destination 'generic/platform=iOS Simulator' \
          -archivePath './CICDFramework' \
          SKIP_INSTALL=NO \
          BUILD_LIBRARIES_FOR_DISTRIBUTION=YES
      - name: Commit
        run: |
          # Stage the file, commit and push
          git add .
          git commit -m "Added framework"
          git push
